steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
images: ['${_IMAGE_NAME}']
substitutions:
  _PROJECT_ID: 'roidtcnov435'
  _TAG_NAME: $SHORT_SHA
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/events-app-internal:${_TAG_NAME}'
